name: vr_challenge
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.2.8+1
  mobx: ^2.2.0
  flutter_modular: ^5.0.3
  cupertino_icons: ^1.0.2
  asuka: ^2.0.2
  equatable: ^2.0.5
  path_provider: ^2.0.14
  flutter_mobx: ^2.0.6+5
  flutter_svg: ^2.0.5
  sqflite_common_ffi: ^2.2.5
  intl: ^0.18.1
  diacritic: ^0.1.3
  flutter_driver:
    sdk: flutter
  string_normalizer: ^0.1.0
  mockito: ^5.4.0
  flutter_launcher_icons:
  flutter_native_splash:

dependency_overrides:
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.22.0
  build_runner: ^2.3.3
  mobx_codegen: ^2.2.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
